### odoo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: odoo:13.0
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: odoo-password
          args:
            - "-i"
            - "base"
            - "--without-demo=all"
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: icgroup
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30069
