apiVersion: v1
data:
  odoo-password: b2Rvbw==
  pgadmin-email: bG1lbmRvbWVtZWJlYW5nMUBteWdlcy5mcg==
  pgadmin-password: YWRtaW4xMjM=
  postgres-password: b2Rvbw==
kind: Secret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: icgroup
